name: job_dart
description: Job for Dart
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  state_notifier: ^0.6.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
